---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "food supply chain"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value truesource below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "food supply chain Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see foodproducer.yaml and distributor.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  mychannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("foodproducer" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.truesource.com

    # Required. list of peers from participating orgs
    peers:
      peer0.foodproducer.truesource.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer0.distributor.truesource.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.foodprocessor.truesource.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.retailer.truesource.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
        
      peer0.consumer.truesource.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - mycc:v0

#
# list of participating organizations in this network
#
organizations:
  foodproducer:
    mspid: foodproducerMSP

    peers:
      - peer0.foodproducer.truesource.com
      

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca-foodproducer

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: channel/crypto-config/peerOrganizations/foodproducer.truesource.com/users/Admin@foodproducer.truesource.com/msp/keystore/8f4df70b3d11f0a5e8de362616a6e4a928cf50331821802aa9b93303fa4eb9f0_sk
    signedCert:
      path: channel/crypto-config/peerOrganizations/foodproducer.truesource.com/users/Admin@foodproducer.truesource.com/msp/signcerts/Admin@foodproducer.truesource.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  distributor:
    mspid: distributorMSP
    peers:
      - peer0.distributor.truesource.com
      
    certificateAuthorities:
      - ca-distributor
    adminPrivateKey:
      path: channel/crypto-config/peerOrganizations/distributor.truesource.com/users/Admin@distributor.truesource.com/msp/keystore/dbb564da6fb831216c317bc123c370bd31833ca00d82d7ee54c42d05d4b8ce9d_sk
    signedCert:
      path: channel/crypto-config/peerOrganizations/distributor.truesource.com/users/Admin@distributor.truesource.com/msp/signcerts/Admin@distributor.truesource.com-cert.pem
      
  foodprocessor:
    mspid: foodprocessorMSP
    peers:
      - peer0.foodprocessor.truesource.com
      
    certificateAuthorities:
      - ca-foodprocessor
    adminPrivateKey:
      path: channel/crypto-config/peerOrganizations/foodprocessor.truesource.com/users/Admin@foodprocessor.truesource.com/msp/keystore/1187b73ca665552624450aa279093a96d8253f613f159e0a7a8193ac679b6bad_sk
    signedCert:
      path: channel/crypto-config/peerOrganizations/foodprocessor.truesource.com/users/Admin@foodprocessor.truesource.com/msp/signcerts/Admin@foodprocessor.truesource.com-cert.pem
      
  retailer:
    mspid: retailerMSP
    peers:
      - peer0.retailer.truesource.com
      
    certificateAuthorities:
      - ca-retailer
    adminPrivateKey:
      path: channel/crypto-config/peerOrganizations/retailer.truesource.com/users/Admin@retailer.truesource.com/msp/keystore/47645734adcd3e3e27f6b10b4173a6486831a364dd80fec1525e4f1e33eebca3_sk
    signedCert:
      path: channel/crypto-config/peerOrganizations/retailer.truesource.com/users/Admin@retailer.truesource.com/msp/signcerts/Admin@retailer.truesource.com-cert.pem
      
  consumer:
    mspid: consumerMSP
    peers:
      - peer0.consumer.truesource.com
      
    certificateAuthorities:
      - ca-consumer
    adminPrivateKey:
      path: channel/crypto-config/peerOrganizations/consumer.truesource.com/users/Admin@consumer.truesource.com/msp/keystore/5bfd5165b5944df27efaf4abdbda22706be842c32f84d79fa09fb9ddd46c3218_sk
    signedCert:
      path: channel/crypto-config/peerOrganizations/consumer.truesource.com/users/Admin@consumer.truesource.com/msp/signcerts/Admin@consumer.truesource.com-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.truesource.com:
    url: grpcs://127.0.0.1:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.truesource.com

    tlsCACerts:
      path: channel/crypto-config/ordererOrganizations/truesource.com/orderers/orderer.truesource.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.foodproducer.truesource.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://127.0.0.1:7051

    grpcOptions:
      ssl-target-name-override: peer0.foodproducer.truesource.com
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/foodproducer.truesource.com/peers/peer0.foodproducer.truesource.com/tls/ca.crt

  peer0.distributor.truesource.com:
    url: grpcs://127.0.0.1:7052
    eventUrl: grpcs://127.0.0.1:7058
    grpcOptions:
      ssl-target-name-override: peer0.distributor.truesource.com
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/distributor.truesource.com/peers/peer0.distributor.truesource.com/tls/ca.crt

  peer0.foodprocessor.truesource.com:
    url: grpcs://127.0.0.1:7056
    grpcOptions:
      ssl-target-name-override: peer0.foodprocessor.truesource.com
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/foodprocessor.truesource.com/peers/peer0.foodprocessor.truesource.com/tls/ca.crt

  peer0.retailer.truesource.com:
    url: grpcs://127.0.0.1:7058
    grpcOptions:
      ssl-target-name-override: peer0.retailer.truesource.com
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/retailer.truesource.com/peers/peer0.retailer.truesource.com/tls/ca.crt
      
   peer0.consumer.truesource.com:
    url: grpcs://127.0.0.1:7060
    grpcOptions:
      ssl-target-name-override: peer0.consumer.truesource.com
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/consumer.truesource.com/peers/peer0.consumer.truesource.com/tls/ca.crt

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-foodproducer:
    url: https://127.0.0.1:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/foodproducer.truesource.com/ca/ca.foodproducer.truesource.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-foodproducer

  ca-distributor:
    url: https://127.0.0.1:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/distributor.truesource.com/ca/ca.distributor.truesource.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-distributor
    
  ca-foodprocessor:
    url: https://127.0.0.1:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/foodprocessor.truesource.com/ca/ca.foodprocessor.truesource.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-foodprocessor
    
  ca-retailer:
    url: https://127.0.0.1:1054
    httpOptions:
      verify: false
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/foodprocessor.truesource.com/ca/ca.foodprocessor.truesource.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-foodprocessor
    
  ca-consumer:
    url: https://127.0.0.1:1154
    httpOptions:
      verify: false
    tlsCACerts:
      path: channel/crypto-config/peerOrganizations/consumer.truesource.com/ca/ca.consumer.truesource.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-consumer